// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SB.Data;

namespace SB.Migrations
{
    [DbContext(typeof(wucha_cloudContext))]
    [Migration("20190710032228_invoiceId")]
    partial class invoiceId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SB.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Activated")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("activated")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Address1")
                        .HasColumnName("address1")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Address2")
                        .HasColumnName("address2")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Address3")
                        .HasColumnName("address3")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("BranchFooter")
                        .HasColumnName("branch_footer")
                        .HasColumnType("text");

                    b.Property<string>("BranchHeader")
                        .HasColumnName("branch_header")
                        .HasColumnType("text");

                    b.Property<string>("BranchPosRecieptFooter")
                        .HasColumnName("branch_pos_reciept_Footer")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("BranchPosRecieptHeader")
                        .HasColumnName("branch_pos_reciept_header")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<int>("CatId")
                        .HasColumnName("cat_id");

                    b.Property<string>("City")
                        .HasColumnName("city")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Country")
                        .HasColumnName("country")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("email")
                        .HasDefaultValueSql("('')")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Fax")
                        .HasColumnName("fax")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("NumberOfTable")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("number_of_table")
                        .HasDefaultValueSql("((16))");

                    b.Property<int>("Numtable")
                        .HasColumnName("numtable");

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Postal1")
                        .HasColumnName("postal1")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Postal2")
                        .HasColumnName("postal2")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Postal3")
                        .HasColumnName("postal3")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasName("IDX_branch_id");

                    b.ToTable("branch");
                });

            modelBuilder.Entity("SB.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AcceptMassEmail")
                        .HasColumnName("accept_mass_email");

                    b.Property<int>("AccessLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("access_level")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Address1")
                        .HasColumnName("address1")
                        .HasMaxLength(50);

                    b.Property<string>("Address1B")
                        .HasColumnName("address1B")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Address2")
                        .HasColumnName("address2")
                        .HasMaxLength(50);

                    b.Property<string>("Address2B")
                        .HasColumnName("address2B")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Address3")
                        .HasColumnName("address3")
                        .HasMaxLength(50);

                    b.Property<string>("ApDdi")
                        .HasColumnName("ap_ddi")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("ApEmail")
                        .HasColumnName("ap_email")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("ApMobile")
                        .HasColumnName("ap_mobile")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("ApName")
                        .HasColumnName("ap_name")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<bool?>("Approved")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("approved")
                        .HasDefaultValueSql("((1))");

                    b.Property<decimal>("Balance")
                        .HasColumnName("balance")
                        .HasColumnType("money");

                    b.Property<string>("Barcode")
                        .HasColumnName("barcode")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("BranchCardId")
                        .HasColumnName("branch_card_id");

                    b.Property<bool>("BuyOnline")
                        .HasColumnName("buy_online");

                    b.Property<string>("CatAccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cat_access")
                        .HasDefaultValueSql("('')")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<byte>("CatAccessGroup")
                        .HasColumnName("cat_access_group");

                    b.Property<string>("City")
                        .HasColumnName("city")
                        .HasMaxLength(50);

                    b.Property<string>("CityB")
                        .HasColumnName("cityB")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Company")
                        .HasColumnName("company")
                        .HasMaxLength(50);

                    b.Property<string>("CompanyB")
                        .HasColumnName("companyB")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Contact")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("contact")
                        .HasDefaultValueSql("('')")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("CorpNumber")
                        .HasColumnName("corp_number")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Country")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("country")
                        .HasDefaultValueSql("('New Zealand')")
                        .HasMaxLength(50);

                    b.Property<string>("CountryB")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("countryB")
                        .HasDefaultValueSql("('New Zealand')")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal>("CreditLimit")
                        .HasColumnName("credit_limit")
                        .HasColumnType("money");

                    b.Property<int>("CreditTerm")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("credit_term")
                        .HasDefaultValueSql("((1))");

                    b.Property<byte>("CurrencyForPurchase")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("currency_for_purchase")
                        .HasDefaultValueSql("((1))");

                    b.Property<int>("CustomerAccessLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("customer_access_level")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnName("date_of_birth")
                        .HasColumnType("date");

                    b.Property<int>("DealerLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("dealer_level")
                        .HasDefaultValueSql("((1))");

                    b.Property<byte?>("Directory")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("directory")
                        .HasDefaultValueSql("((1))");

                    b.Property<double>("Discount")
                        .HasColumnName("discount");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Fax")
                        .HasColumnName("fax")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<double>("GstRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("gst_rate")
                        .HasDefaultValueSql("((0.15))");

                    b.Property<bool?>("HasExpired")
                        .HasColumnName("has_expired");

                    b.Property<bool>("IsAddup")
                        .HasColumnName("is_addup");

                    b.Property<bool>("IsBranch")
                        .HasColumnName("is_branch");

                    b.Property<byte>("Language")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("language")
                        .HasDefaultValueSql("((1))");

                    b.Property<int?>("LastBranchId")
                        .HasColumnName("last_branch_id");

                    b.Property<DateTime>("LastPostTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("last_post_time")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("M1")
                        .HasColumnName("m1")
                        .HasColumnType("money");

                    b.Property<decimal>("M10")
                        .HasColumnName("m10")
                        .HasColumnType("money");

                    b.Property<decimal>("M11")
                        .HasColumnName("m11")
                        .HasColumnType("money");

                    b.Property<decimal>("M12")
                        .HasColumnName("m12")
                        .HasColumnType("money");

                    b.Property<decimal>("M2")
                        .HasColumnName("m2")
                        .HasColumnType("money");

                    b.Property<decimal>("M3")
                        .HasColumnName("m3")
                        .HasColumnType("money");

                    b.Property<decimal>("M4")
                        .HasColumnName("m4")
                        .HasColumnType("money");

                    b.Property<decimal>("M5")
                        .HasColumnName("m5")
                        .HasColumnType("money");

                    b.Property<decimal>("M6")
                        .HasColumnName("m6")
                        .HasColumnType("money");

                    b.Property<decimal>("M7")
                        .HasColumnName("m7")
                        .HasColumnType("money");

                    b.Property<decimal>("M8")
                        .HasColumnName("m8")
                        .HasColumnType("money");

                    b.Property<decimal>("M9")
                        .HasColumnName("m9")
                        .HasColumnType("money");

                    b.Property<double?>("MDiscountRate")
                        .HasColumnName("m_discount_rate");

                    b.Property<int?>("MainCardId")
                        .HasColumnName("main_card_id");

                    b.Property<string>("MemberId")
                        .HasColumnName("member_id")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Mobile")
                        .HasColumnName("mobile")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.Property<string>("NameB")
                        .HasColumnName("nameB")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("NameCn")
                        .HasColumnName("name_cn")
                        .HasMaxLength(150);

                    b.Property<string>("Nationality")
                        .HasColumnName("nationality")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<bool>("NoSysQuote")
                        .HasColumnName("no_sys_quote");

                    b.Property<string>("Note")
                        .HasColumnName("note")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<byte>("OurBranch")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("our_branch")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("PersonalId")
                        .HasColumnName("personal_id");

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("PmDdi")
                        .HasColumnName("pm_ddi")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("PmEmail")
                        .HasColumnName("pm_email")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("PmMobile")
                        .HasColumnName("pm_mobile")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("Points")
                        .HasColumnName("points");

                    b.Property<string>("PostCode")
                        .HasColumnName("post_code")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Postal1")
                        .HasColumnName("postal1")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Postal2")
                        .HasColumnName("postal2")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Postal3")
                        .HasColumnName("postal3")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("PriceLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("price_level")
                        .HasDefaultValueSql("((1))");

                    b.Property<decimal>("PurchaseAverage")
                        .HasColumnName("purchase_average")
                        .HasColumnType("money");

                    b.Property<decimal>("PurchaseNza")
                        .HasColumnName("purchase_nza")
                        .HasColumnType("money");

                    b.Property<DateTime>("RegisterDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("register_date")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("Registered")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("registered")
                        .HasDefaultValueSql("((1))");

                    b.Property<int?>("Sales")
                        .HasColumnName("sales");

                    b.Property<decimal>("ShippingFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("shipping_fee")
                        .HasColumnType("money")
                        .HasDefaultValueSql("((10))");

                    b.Property<string>("ShortName")
                        .HasColumnName("short_name")
                        .HasMaxLength(50);

                    b.Property<string>("SmDdi")
                        .HasColumnName("sm_ddi")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("SmEmail")
                        .HasColumnName("sm_email")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("SmMobile")
                        .HasColumnName("sm_mobile")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("SmName")
                        .HasColumnName("sm_name")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<bool>("StopOrder")
                        .HasColumnName("stop_order");

                    b.Property<string>("StopOrderReason")
                        .HasColumnName("stop_order_reason")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("TechEmail")
                        .HasColumnName("tech_email")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<long?>("TotalOnlineOrderPoint")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("total_online_order_point")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("TotalPosts")
                        .HasColumnName("total_posts");

                    b.Property<string>("TradingName")
                        .HasColumnName("trading_name")
                        .HasMaxLength(50);

                    b.Property<decimal>("TransTotal")
                        .HasColumnName("trans_total")
                        .HasColumnType("money");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("type")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool?>("Updated")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("updated")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Web")
                        .HasColumnName("web")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<byte>("WorkingOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("working_on")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id");

                    b.ToTable("card");
                });

            modelBuilder.Entity("SB.Models.CodeRelations", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int>("AllocatedStock")
                        .HasColumnName("allocated_stock");

                    b.Property<decimal>("AverageCost")
                        .HasColumnName("average_cost")
                        .HasColumnType("money");

                    b.Property<string>("Barcode")
                        .HasColumnName("barcode")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal>("BasePrice")
                        .HasColumnName("base_price")
                        .HasColumnType("money");

                    b.Property<string>("Brand")
                        .HasColumnName("brand")
                        .HasMaxLength(50);

                    b.Property<string>("Cat")
                        .HasColumnName("cat")
                        .HasMaxLength(50);

                    b.Property<bool>("Clearance")
                        .HasColumnName("clearance");

                    b.Property<int>("Code")
                        .HasColumnName("code");

                    b.Property<byte?>("ComingSoon")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("coming_soon")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("CostAccount")
                        .HasColumnName("cost_account");

                    b.Property<int>("CostofsalesAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("costofsales_account")
                        .HasDefaultValueSql("((5111))");

                    b.Property<byte>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("currency")
                        .HasDefaultValueSql("((1))");

                    b.Property<int>("Disappeared")
                        .HasColumnName("disappeared");

                    b.Property<double?>("ExchangeRate")
                        .HasColumnName("exchange_rate");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnName("expire_date")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("ForeignSupplierPrice")
                        .HasColumnName("foreign_supplier_price")
                        .HasColumnType("money");

                    b.Property<bool?>("HasScale")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("has_scale")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool?>("Hot")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("hot")
                        .HasDefaultValueSql("((1))");

                    b.Property<byte?>("Inactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("inactive")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("IncomeAccount")
                        .HasColumnName("income_account");

                    b.Property<int>("InnerPack")
                        .HasColumnName("inner_pack");

                    b.Property<string>("InventoryAccount")
                        .HasColumnName("inventory_account")
                        .HasMaxLength(50);

                    b.Property<bool>("IsAddup")
                        .HasColumnName("is_addup");

                    b.Property<bool>("IsCutSp")
                        .HasColumnName("is_cut_sp");

                    b.Property<bool>("IsMain")
                        .HasColumnName("is_main");

                    b.Property<bool>("IsMandatory")
                        .HasColumnName("is_mandatory");

                    b.Property<bool>("IsProduction")
                        .HasColumnName("is_production");

                    b.Property<bool>("IsService")
                        .HasColumnName("is_service");

                    b.Property<bool?>("IsSpecial")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("is_special")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool>("IsSync")
                        .HasColumnName("is_sync");

                    b.Property<decimal>("LevelPrice0")
                        .HasColumnName("level_price0")
                        .HasColumnType("money");

                    b.Property<decimal>("LevelPrice1")
                        .HasColumnName("level_price1")
                        .HasColumnType("money");

                    b.Property<decimal>("LevelPrice2")
                        .HasColumnName("level_price2")
                        .HasColumnType("money");

                    b.Property<decimal>("LevelPrice3")
                        .HasColumnName("level_price3")
                        .HasColumnType("money");

                    b.Property<decimal>("LevelPrice4")
                        .HasColumnName("level_price4")
                        .HasColumnType("money");

                    b.Property<decimal>("LevelPrice5")
                        .HasColumnName("level_price5")
                        .HasColumnType("money");

                    b.Property<decimal>("LevelPrice6")
                        .HasColumnName("level_price6")
                        .HasColumnType("money");

                    b.Property<double>("LevelRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("level_rate")
                        .HasDefaultValueSql("((1))");

                    b.Property<double>("LevelRate1")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("level_rate1")
                        .HasDefaultValueSql("((2))");

                    b.Property<double>("LevelRate2")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("level_rate2")
                        .HasDefaultValueSql("((1.5))");

                    b.Property<double>("LevelRate3")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("level_rate3")
                        .HasDefaultValueSql("((1.2))");

                    b.Property<double>("LevelRate4")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("level_rate4")
                        .HasDefaultValueSql("((1.1))");

                    b.Property<double>("LevelRate5")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("level_rate5")
                        .HasDefaultValueSql("((1))");

                    b.Property<double>("LevelRate6")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("level_rate6")
                        .HasDefaultValueSql("((0.9))");

                    b.Property<double?>("LevelRate7")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("level_rate7")
                        .HasDefaultValueSql("((2))");

                    b.Property<double?>("LevelRate8")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("level_rate8")
                        .HasDefaultValueSql("((2))");

                    b.Property<double?>("LevelRate9")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("level_rate9")
                        .HasDefaultValueSql("((2))");

                    b.Property<int>("LowStock")
                        .HasColumnName("low_stock");

                    b.Property<decimal>("ManualCostFrd")
                        .HasColumnName("manual_cost_frd")
                        .HasColumnType("money");

                    b.Property<decimal>("ManualCostNzd")
                        .HasColumnName("manual_cost_nzd")
                        .HasColumnType("money");

                    b.Property<double>("ManualExchangeRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("manual_exchange_rate")
                        .HasDefaultValueSql("((1))");

                    b.Property<int>("Moq")
                        .HasColumnName("moq");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(255);

                    b.Property<string>("NameCn")
                        .HasColumnName("name_cn")
                        .HasMaxLength(500);

                    b.Property<string>("NameDes")
                        .HasColumnName("name_des")
                        .HasMaxLength(500);

                    b.Property<double?>("NormalPrice")
                        .HasColumnName("normal_price");

                    b.Property<decimal>("NzdFreight")
                        .HasColumnName("nzd_freight")
                        .HasColumnType("money");

                    b.Property<string>("PackageBarcode1")
                        .HasColumnName("package_barcode1")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("PackageBarcode2")
                        .HasColumnName("package_barcode2")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("PackageBarcode3")
                        .HasColumnName("package_barcode3")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<double?>("PackagePrice1")
                        .HasColumnName("package_price1");

                    b.Property<double?>("PackagePrice2")
                        .HasColumnName("package_price2");

                    b.Property<double?>("PackagePrice3")
                        .HasColumnName("package_price3");

                    b.Property<int?>("PackageQty1")
                        .HasColumnName("package_qty1");

                    b.Property<int?>("PackageQty2")
                        .HasColumnName("package_qty2");

                    b.Property<int?>("PackageQty3")
                        .HasColumnName("package_qty3");

                    b.Property<int>("Points")
                        .HasColumnName("points");

                    b.Property<bool?>("Popular")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("popular")
                        .HasDefaultValueSql("((1))");

                    b.Property<decimal>("Price1")
                        .HasColumnName("price1")
                        .HasColumnType("money");

                    b.Property<decimal>("Price2")
                        .HasColumnName("price2")
                        .HasColumnType("money");

                    b.Property<decimal>("Price3")
                        .HasColumnName("price3")
                        .HasColumnType("money");

                    b.Property<decimal>("Price4")
                        .HasColumnName("price4")
                        .HasColumnType("money");

                    b.Property<decimal>("Price5")
                        .HasColumnName("price5")
                        .HasColumnType("money");

                    b.Property<decimal>("Price6")
                        .HasColumnName("price6")
                        .HasColumnType("money");

                    b.Property<decimal>("Price7")
                        .HasColumnName("price7")
                        .HasColumnType("money");

                    b.Property<decimal>("Price8")
                        .HasColumnName("price8")
                        .HasColumnType("money");

                    b.Property<decimal>("Price9")
                        .HasColumnName("price9")
                        .HasColumnType("money");

                    b.Property<decimal>("PriceSystem")
                        .HasColumnName("price_system")
                        .HasColumnType("money");

                    b.Property<byte?>("Promotion")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("promotion")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("QposQtyBreak")
                        .HasColumnName("qpos_qty_break");

                    b.Property<int>("QtyBreak1")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("qty_break1")
                        .HasDefaultValueSql("((5))");

                    b.Property<int?>("QtyBreak2")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("qty_break2")
                        .HasDefaultValueSql("((10))");

                    b.Property<int?>("QtyBreak3")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("qty_break3")
                        .HasDefaultValueSql("((20))");

                    b.Property<int?>("QtyBreak4")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("qty_break4")
                        .HasDefaultValueSql("((50))");

                    b.Property<int?>("QtyBreak5")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("qty_break5")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("QtyBreak6")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("qty_break6")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("QtyBreak7")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("qty_break7")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("QtyBreak8")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("qty_break8")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("QtyBreak9")
                        .HasColumnName("qty_break9");

                    b.Property<double>("QtyBreakDiscount1")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("qty_break_discount1")
                        .HasDefaultValueSql("((1))");

                    b.Property<double?>("QtyBreakDiscount2")
                        .HasColumnName("qty_break_discount2");

                    b.Property<double?>("QtyBreakDiscount3")
                        .HasColumnName("qty_break_discount3");

                    b.Property<double?>("QtyBreakDiscount4")
                        .HasColumnName("qty_break_discount4");

                    b.Property<double?>("QtyBreakDiscount5")
                        .HasColumnName("qty_break_discount5");

                    b.Property<double?>("QtyBreakDiscount6")
                        .HasColumnName("qty_break_discount6");

                    b.Property<double?>("QtyBreakDiscount7")
                        .HasColumnName("qty_break_discount7");

                    b.Property<double?>("QtyBreakDiscount8")
                        .HasColumnName("qty_break_discount8");

                    b.Property<double?>("QtyBreakDiscount9")
                        .HasColumnName("qty_break_discount9");

                    b.Property<decimal?>("QtyBreakPrice1")
                        .HasColumnName("qty_break_price1")
                        .HasColumnType("money");

                    b.Property<decimal?>("QtyBreakPrice10")
                        .HasColumnName("qty_break_price10")
                        .HasColumnType("money");

                    b.Property<decimal?>("QtyBreakPrice2")
                        .HasColumnName("qty_break_price2")
                        .HasColumnType("money");

                    b.Property<decimal?>("QtyBreakPrice3")
                        .HasColumnName("qty_break_price3")
                        .HasColumnType("money");

                    b.Property<decimal?>("QtyBreakPrice4")
                        .HasColumnName("qty_break_price4")
                        .HasColumnType("money");

                    b.Property<decimal?>("QtyBreakPrice5")
                        .HasColumnName("qty_break_price5")
                        .HasColumnType("money");

                    b.Property<decimal?>("QtyBreakPrice6")
                        .HasColumnName("qty_break_price6")
                        .HasColumnType("money");

                    b.Property<decimal?>("QtyBreakPrice7")
                        .HasColumnName("qty_break_price7")
                        .HasColumnType("money");

                    b.Property<decimal?>("QtyBreakPrice8")
                        .HasColumnName("qty_break_price8")
                        .HasColumnType("money");

                    b.Property<decimal?>("QtyBreakPrice9")
                        .HasColumnName("qty_break_price9")
                        .HasColumnType("money");

                    b.Property<double>("Rate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("rate")
                        .HasDefaultValueSql("((1.1))");

                    b.Property<bool>("RealStock")
                        .HasColumnName("real_stock");

                    b.Property<string>("RefCode")
                        .HasColumnName("ref_code")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<decimal>("Rrp")
                        .HasColumnName("rrp")
                        .HasColumnType("money");

                    b.Property<string>("SCat")
                        .HasColumnName("s_cat")
                        .HasMaxLength(50);

                    b.Property<bool>("Skip")
                        .HasColumnName("skip");

                    b.Property<string>("SkuCode")
                        .HasColumnName("sku_code")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<double?>("SpecialPrice")
                        .HasColumnName("special_price");

                    b.Property<DateTime?>("SpecialPriceEndDate")
                        .HasColumnName("special_price_end_date")
                        .HasColumnType("datetime");

                    b.Property<string>("SsCat")
                        .HasColumnName("ss_cat")
                        .HasMaxLength(50);

                    b.Property<string>("StockLocation")
                        .HasColumnName("stock_location")
                        .HasMaxLength(50);

                    b.Property<string>("Supplier")
                        .HasColumnName("supplier")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("SupplierCode")
                        .HasColumnName("supplier_code")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal?>("SupplierPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("supplier_price")
                        .HasColumnType("money")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("TaxCode")
                        .HasColumnName("tax_code")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<double>("TaxRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tax_rate")
                        .HasDefaultValueSql("((0.15))");

                    b.Property<bool>("WebItem")
                        .HasColumnName("web_item");

                    b.Property<double?>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("weight")
                        .HasDefaultValueSql("((10))");

                    b.HasKey("Id");

                    b.HasIndex("Cat")
                        .HasName("IDX_code_relations_cat");

                    b.HasIndex("Clearance")
                        .HasName("IDX_code_relations_clearance");

                    b.HasIndex("Code")
                        .HasName("IDX_code_relations_code");

                    b.HasIndex("Id")
                        .HasName("IDX_code_relations_id");

                    b.HasIndex("SCat")
                        .HasName("IDX_code_relations_scat");

                    b.HasIndex("SsCat")
                        .HasName("IDX_code_relations_sscat");

                    b.HasIndex("SupplierCode")
                        .HasName("IDX_code_relations_spl_code");

                    b.ToTable("code_relations");
                });

            modelBuilder.Entity("SB.Models.EnumTable", b =>
                {
                    b.Property<string>("Class")
                        .HasColumnName("class")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<string>("ClassType")
                        .HasColumnName("class_type")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.Property<string>("ShortName")
                        .HasColumnName("short_name")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<bool?>("Updated")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("updated")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Class", "Id");

                    b.HasIndex("Class")
                        .HasName("IDX_enum_class");

                    b.HasIndex("Id")
                        .HasName("IDX_enum_class_id");

                    b.HasIndex("Name")
                        .HasName("IDX_enum_name");

                    b.ToTable("enum");
                });

            modelBuilder.Entity("SB.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address1")
                        .HasColumnName("address1")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Address2")
                        .HasColumnName("address2")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Address3")
                        .HasColumnName("address3")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<int>("Agent")
                        .HasColumnName("agent");

                    b.Property<decimal?>("AmountPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("amount_paid")
                        .HasColumnType("money")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Barcode")
                        .HasColumnName("barcode")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("Branch")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("branch")
                        .HasDefaultValueSql("((1))");

                    b.Property<int>("CardId")
                        .HasColumnName("card_id");

                    b.Property<DateTime>("CommitDate")
                        .HasColumnName("commit_date")
                        .HasColumnType("datetime");

                    b.Property<string>("Company")
                        .HasColumnName("company")
                        .HasMaxLength(255);

                    b.Property<string>("CustPonumber")
                        .HasColumnName("cust_ponumber")
                        .HasMaxLength(50);

                    b.Property<double>("CustomerGst")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("customer_gst")
                        .HasDefaultValueSql("((0.125))");

                    b.Property<string>("DebugInfo")
                        .HasColumnName("debug_info")
                        .HasMaxLength(2048)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Fax")
                        .HasColumnName("fax")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal?>("Freight")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("freight")
                        .HasColumnType("money")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool>("GstInclusive")
                        .HasColumnName("gst_inclusive");

                    b.Property<int>("InvoiceNumber")
                        .HasColumnName("invoice_number");

                    b.Property<bool>("IsRedeem")
                        .HasColumnName("is_redeem");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(250);

                    b.Property<bool>("NoIndividualPrice")
                        .HasColumnName("no_individual_price");

                    b.Property<bool>("Paid")
                        .HasColumnName("paid");

                    b.Property<byte?>("PaymentType")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("payment_type")
                        .HasDefaultValueSql("((2))");

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("PickUpTime")
                        .HasColumnName("pick_up_time")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("Points")
                        .HasColumnName("points");

                    b.Property<string>("Postal1")
                        .HasColumnName("postal1")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Postal2")
                        .HasColumnName("postal2")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Postal3")
                        .HasColumnName("postal3")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal?>("Price")
                        .HasColumnName("price")
                        .HasColumnType("money");

                    b.Property<DateTime>("RecordDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("record_date")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("Refunded")
                        .HasColumnName("refunded");

                    b.Property<string>("Sales")
                        .HasColumnName("sales")
                        .HasMaxLength(250);

                    b.Property<string>("SalesNote")
                        .HasColumnName("sales_note")
                        .HasColumnType("ntext");

                    b.Property<byte>("SalesType")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("sales_type")
                        .HasDefaultValueSql("((1))");

                    b.Property<byte>("ShippingMethod")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("shipping_method")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Shipto")
                        .HasColumnName("shipto")
                        .HasMaxLength(1024);

                    b.Property<bool>("SpecialShipto")
                        .HasColumnName("special_shipto");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("status")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool>("System")
                        .HasColumnName("system");

                    b.Property<decimal?>("Tax")
                        .HasColumnName("tax")
                        .HasColumnType("money");

                    b.Property<decimal?>("Total")
                        .HasColumnName("total")
                        .HasColumnType("money");

                    b.Property<string>("TradingName")
                        .HasColumnName("trading_name")
                        .HasMaxLength(255);

                    b.Property<string>("TransFailedReason")
                        .HasColumnName("trans_failed_reason")
                        .HasMaxLength(1024)
                        .IsUnicode(false);

                    b.Property<byte?>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("type")
                        .HasDefaultValueSql("((3))");

                    b.Property<int>("Uploaded")
                        .HasColumnName("uploaded");

                    b.HasKey("Id");

                    b.HasIndex("Branch")
                        .HasName("IDX_invoice_branch");

                    b.HasIndex("CardId")
                        .HasName("IDX_invoice_card_id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasName("IDX_invoice_number");

                    b.HasIndex("Type")
                        .HasName("IDX_invoice_type");

                    b.ToTable("invoice");
                });

            modelBuilder.Entity("SB.Models.OrderItem", b =>
                {
                    b.Property<int>("Kid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("kid")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cat")
                        .HasColumnName("cat")
                        .HasMaxLength(50);

                    b.Property<int>("Code")
                        .HasColumnName("code");

                    b.Property<decimal>("CommitPrice")
                        .HasColumnName("commit_price")
                        .HasColumnType("money");

                    b.Property<double>("DiscountPercent")
                        .HasColumnName("discount_percent");

                    b.Property<string>("Eta")
                        .HasColumnName("eta")
                        .HasMaxLength(50);

                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnName("item_name")
                        .HasMaxLength(255);

                    b.Property<string>("ItemNameCn")
                        .HasColumnName("item_name_cn")
                        .HasMaxLength(500);

                    b.Property<bool>("Kit")
                        .HasColumnName("kit");

                    b.Property<int?>("Krid")
                        .HasColumnName("krid");

                    b.Property<string>("Note")
                        .HasColumnName("note")
                        .HasMaxLength(255);

                    b.Property<decimal?>("OrderTotal")
                        .HasColumnName("order_total")
                        .HasColumnType("money");

                    b.Property<int>("Part")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("part")
                        .HasDefaultValueSql("((-1))");

                    b.Property<int>("Points")
                        .HasColumnName("points");

                    b.Property<double>("Quantity")
                        .HasColumnName("quantity");

                    b.Property<string>("SCat")
                        .HasColumnName("s_cat")
                        .HasMaxLength(50);

                    b.Property<string>("SsCat")
                        .HasColumnName("ss_cat")
                        .HasMaxLength(50);

                    b.Property<string>("StationId")
                        .HasColumnName("station_id")
                        .HasMaxLength(50);

                    b.Property<string>("Supplier")
                        .HasColumnName("supplier")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasColumnName("supplier_code")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal>("SupplierPrice")
                        .HasColumnName("supplier_price")
                        .HasColumnType("money");

                    b.Property<bool>("SysSpecial")
                        .HasColumnName("sys_special");

                    b.Property<bool>("System")
                        .HasColumnName("system");

                    b.Property<string>("TaxCode")
                        .HasColumnName("tax_code")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<double?>("TaxRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tax_rate")
                        .HasDefaultValueSql("((0.15))");

                    b.HasKey("Kid");

                    b.HasIndex("Code")
                        .HasName("IDX_order_item_code");

                    b.HasIndex("Id")
                        .HasName("IDX_order_item_id");

                    b.HasIndex("Kid")
                        .HasName("IDX_order_item_krid");

                    b.HasIndex("Kit")
                        .HasName("IDX_order_item_kit");

                    b.HasIndex("SupplierCode")
                        .HasName("IDX_order_item_supplier_code");

                    b.ToTable("order_item");
                });

            modelBuilder.Entity("SB.Models.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Agent")
                        .HasColumnName("agent");

                    b.Property<int>("Branch")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("branch")
                        .HasDefaultValueSql("((1))");

                    b.Property<int>("CardId")
                        .HasColumnName("card_id");

                    b.Property<string>("Contact")
                        .HasColumnName("contact")
                        .HasMaxLength(250);

                    b.Property<int?>("CreditOrderId")
                        .HasColumnName("credit_order_id");

                    b.Property<double>("CustomerGst")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("customer_gst")
                        .HasDefaultValueSql("((0.125))");

                    b.Property<DateTime?>("DateShipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("date_shipped")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DealerCustomerName")
                        .HasColumnName("dealer_customer_name")
                        .HasMaxLength(250);

                    b.Property<bool>("DealerDraft")
                        .HasColumnName("dealer_draft");

                    b.Property<decimal>("DealerTotal")
                        .HasColumnName("dealer_total")
                        .HasColumnType("money");

                    b.Property<string>("DebugInfo")
                        .HasColumnName("debug_info")
                        .HasMaxLength(1024)
                        .IsUnicode(false);

                    b.Property<string>("DeliveryNumber")
                        .HasColumnName("delivery_number")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("ExpectingDate")
                        .HasColumnName("expecting_date")
                        .HasMaxLength(250);

                    b.Property<decimal>("Freight")
                        .HasColumnName("freight")
                        .HasColumnType("money");

                    b.Property<bool>("GstInclusive")
                        .HasColumnName("gst_inclusive");

                    b.Property<int?>("InvoiceNumber")
                        .HasColumnName("invoice_number");

                    b.Property<bool>("IsRedeem")
                        .HasColumnName("is_redeem");

                    b.Property<int?>("LockedBy")
                        .HasColumnName("locked_by");

                    b.Property<bool>("NoIndividualPrice")
                        .HasColumnName("no_individual_price");

                    b.Property<int>("Number")
                        .HasColumnName("number");

                    b.Property<bool?>("OrderDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("order_deleted")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool>("Paid")
                        .HasColumnName("paid");

                    b.Property<int>("Part")
                        .HasColumnName("part");

                    b.Property<byte>("PaymentType")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("payment_type")
                        .HasDefaultValueSql("((3))");

                    b.Property<string>("PickUpTime")
                        .HasColumnName("pick_up_time")
                        .HasMaxLength(250);

                    b.Property<string>("PoNumber")
                        .HasColumnName("po_number")
                        .HasMaxLength(250);

                    b.Property<int>("Points")
                        .HasColumnName("points");

                    b.Property<int?>("PurchaseId")
                        .HasColumnName("purchase_id");

                    b.Property<decimal>("QuoteTotal")
                        .HasColumnName("quote_total")
                        .HasColumnType("money");

                    b.Property<DateTime>("RecordDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("record_date")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Sales")
                        .HasColumnName("sales");

                    b.Property<int?>("SalesManager")
                        .HasColumnName("sales_manager");

                    b.Property<string>("SalesNote")
                        .HasColumnName("sales_note")
                        .HasColumnType("ntext");

                    b.Property<bool>("ShipAsParts")
                        .HasColumnName("ship_as_parts");

                    b.Property<int?>("Shipby")
                        .HasColumnName("shipby");

                    b.Property<byte>("ShippingMethod")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("shipping_method")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Shipto")
                        .HasColumnName("shipto")
                        .HasMaxLength(1024);

                    b.Property<bool>("SpecialShipto")
                        .HasColumnName("special_shipto");

                    b.Property<string>("StationId")
                        .HasColumnName("station_id")
                        .HasMaxLength(50);

                    b.Property<byte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("status")
                        .HasDefaultValueSql("((1))");

                    b.Property<byte>("StatusOrderonly")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("status_orderonly")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool>("System")
                        .HasColumnName("system");

                    b.Property<string>("TableName")
                        .HasColumnName("table_name")
                        .HasMaxLength(50);

                    b.Property<string>("Ticket")
                        .HasColumnName("ticket")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("TimeLocked")
                        .HasColumnName("time_locked")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("TotalDiscount")
                        .HasColumnName("total_discount")
                        .HasColumnType("money");

                    b.Property<decimal?>("TotalSpecial")
                        .HasColumnName("total_special")
                        .HasColumnType("money");

                    b.Property<string>("TransFailedReason")
                        .HasColumnName("trans_failed_reason")
                        .HasMaxLength(1024)
                        .IsUnicode(false);

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("type")
                        .HasDefaultValueSql("((2))");

                    b.Property<bool?>("Unchecked")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("unchecked")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .HasName("IDX_orders_card_id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasName("IDX_orders_id");

                    b.HasIndex("InvoiceNumber")
                        .HasName("IDX_orders_invoice_number");

                    b.HasIndex("Sales")
                        .HasName("IDX_orders_sales");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("SB.Models.Sales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cat")
                        .HasColumnName("cat")
                        .HasMaxLength(50);

                    b.Property<int>("Code")
                        .HasColumnName("code");

                    b.Property<decimal>("CommitPrice")
                        .HasColumnName("commit_price")
                        .HasColumnType("money");

                    b.Property<int?>("CostofsalesAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("costofsales_account")
                        .HasDefaultValueSql("((5111))");

                    b.Property<double>("DiscountPercent")
                        .HasColumnName("discount_percent");

                    b.Property<int?>("IncomeAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("income_account")
                        .HasDefaultValueSql("((4111))");

                    b.Property<int?>("InventoryAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("inventory_account")
                        .HasDefaultValueSql("((1121))");

                    b.Property<int>("InvoiceNumber")
                        .HasColumnName("invoice_number");

                    b.Property<bool>("Kit")
                        .HasColumnName("kit");

                    b.Property<int?>("Krid")
                        .HasColumnName("krid");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(255);

                    b.Property<string>("NameCn")
                        .HasColumnName("name_cn")
                        .HasMaxLength(500);

                    b.Property<decimal>("NormalPrice")
                        .HasColumnName("normal_price")
                        .HasColumnType("money");

                    b.Property<string>("Note")
                        .HasColumnName("note")
                        .HasMaxLength(1024);

                    b.Property<int?>("Owner")
                        .HasColumnName("owner");

                    b.Property<byte?>("PStatus")
                        .HasColumnName("p_status");

                    b.Property<int?>("Part")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("part")
                        .HasDefaultValueSql("((-1))");

                    b.Property<int?>("ProcessedBy")
                        .HasColumnName("processed_by");

                    b.Property<double>("Quantity")
                        .HasColumnName("quantity");

                    b.Property<string>("SCat")
                        .HasColumnName("s_cat")
                        .HasMaxLength(50);

                    b.Property<decimal?>("SalesTotal")
                        .HasColumnName("sales_total")
                        .HasColumnType("money");

                    b.Property<string>("SerialNumber")
                        .HasColumnName("serial_number")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("ShipDate")
                        .HasColumnName("ship_date")
                        .HasColumnType("datetime");

                    b.Property<byte?>("Shipby")
                        .HasColumnName("shipby");

                    b.Property<string>("SsCat")
                        .HasColumnName("ss_cat")
                        .HasMaxLength(50);

                    b.Property<string>("StationId")
                        .HasColumnName("station_id")
                        .HasMaxLength(50);

                    b.Property<byte?>("Status")
                        .HasColumnName("status");

                    b.Property<int?>("StockAtSales")
                        .HasColumnName("stock_at_sales");

                    b.Property<string>("Supplier")
                        .HasColumnName("supplier")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("SupplierCode")
                        .HasColumnName("supplier_code")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal>("SupplierPrice")
                        .HasColumnName("supplier_price")
                        .HasColumnType("money");

                    b.Property<bool>("SysSpecial")
                        .HasColumnName("sys_special");

                    b.Property<bool>("System")
                        .HasColumnName("system");

                    b.Property<string>("TaxCode")
                        .HasColumnName("tax_code")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<double?>("TaxRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tax_rate")
                        .HasDefaultValueSql("((0.15))");

                    b.Property<string>("Ticket")
                        .HasColumnName("ticket")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<bool>("Used")
                        .HasColumnName("used");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasName("IDX_sales_code");

                    b.HasIndex("InvoiceNumber")
                        .HasName("IDX_sales_invoice_number");

                    b.HasIndex("Kit")
                        .HasName("IDX_sales_kit");

                    b.HasIndex("Krid")
                        .HasName("IDX_sales_krid");

                    b.HasIndex("Part")
                        .HasName("IDX_sales_part");

                    b.HasIndex("Status")
                        .HasName("IDX_sales_status");

                    b.HasIndex("System")
                        .HasName("IDX_sales_system");

                    b.ToTable("sales");
                });

            modelBuilder.Entity("SB.Models.TranDetail", b =>
                {
                    b.Property<int>("Kid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("kid")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bank")
                        .HasColumnName("bank")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("BillPaymentNo")
                        .HasColumnName("bill_payment_no")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Branch")
                        .HasColumnName("branch")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("CardId")
                        .HasColumnName("card_id");

                    b.Property<bool>("Cleaned")
                        .HasColumnName("cleaned");

                    b.Property<decimal>("Credit")
                        .HasColumnName("credit")
                        .HasColumnType("money");

                    b.Property<int?>("CreditId")
                        .HasColumnName("credit_id");

                    b.Property<decimal>("CurrencyLoss")
                        .HasColumnName("currency_loss")
                        .HasColumnType("money");

                    b.Property<decimal?>("DestBalance")
                        .HasColumnName("dest_balance")
                        .HasColumnType("money");

                    b.Property<decimal>("Finance")
                        .HasColumnName("finance")
                        .HasColumnType("money");

                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnName("invoice_number")
                        .HasMaxLength(4096)
                        .IsUnicode(false);

                    b.Property<string>("Note")
                        .HasColumnName("note")
                        .HasMaxLength(1024);

                    b.Property<string>("PaidBy")
                        .HasColumnName("paid_by")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("PaymentMethod")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentRef")
                        .HasColumnName("payment_ref")
                        .HasMaxLength(150);

                    b.Property<decimal?>("SourceBalance")
                        .HasColumnName("source_balance")
                        .HasColumnType("money");

                    b.Property<int?>("StaffId")
                        .HasColumnName("staff_id");

                    b.Property<int?>("TableId")
                        .HasColumnName("table_id");

                    b.Property<bool?>("TillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("till_id")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime?>("TransDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("trans_date")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Kid");

                    b.HasIndex("CardId")
                        .HasName("IDX_tran_detail_card_id");

                    b.HasIndex("Id")
                        .HasName("IDX_tran_detail_id");

                    b.HasIndex("StaffId");

                    b.ToTable("tran_detail");
                });

            modelBuilder.Entity("SB.Models.TranInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AmountApplied")
                        .HasColumnName("amount_applied")
                        .HasColumnType("money");

                    b.Property<bool>("Purchase")
                        .HasColumnName("purchase");

                    b.Property<int>("TranId")
                        .HasColumnName("tran_id");

                    b.Property<int>("invoiceId");

                    b.Property<int>("invoice_number")
                        .HasColumnName("invoice_number");

                    b.Property<int?>("payment_method");

                    b.HasKey("Id");

                    b.HasIndex("Purchase")
                        .HasName("IDX_tran_invoice_purchase");

                    b.HasIndex("TranId")
                        .HasName("IDX_tran_invoice_tranid");

                    b.HasIndex("invoiceId");

                    b.ToTable("tran_invoice");
                });

            modelBuilder.Entity("SB.Models.Trans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnName("amount")
                        .HasColumnType("money");

                    b.Property<bool>("Banked")
                        .HasColumnName("banked");

                    b.Property<byte>("Branch")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("branch")
                        .HasDefaultValueSql("((1))");

                    b.Property<int?>("Dest")
                        .HasColumnName("dest");

                    b.Property<decimal?>("DestAmount")
                        .HasColumnName("dest_amount")
                        .HasColumnType("money");

                    b.Property<int?>("Source")
                        .HasColumnName("source");

                    b.Property<int?>("TransBankId")
                        .HasColumnName("trans_bank_id");

                    b.Property<int?>("TransDate")
                        .HasColumnName("trans_date");

                    b.HasKey("Id");

                    b.HasIndex("Banked")
                        .HasName("IDX_trans_banked");

                    b.HasIndex("Branch")
                        .HasName("IDX_trans_branch");

                    b.ToTable("trans");
                });

            modelBuilder.Entity("SB.Models.TranInvoice", b =>
                {
                    b.HasOne("SB.Models.Invoice", "invoice")
                        .WithMany("tranInvoice")
                        .HasForeignKey("invoiceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
